# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'p2pLending' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for p2pLending

pod 'Web3Swift.io'

  target 'p2pLendingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'p2pLendingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
