export default {
  icoState: {
    // icoGoal: null,
    // icoEtherBalance: null,
    // isIcoActive: null,
    // totalTokenSupply: null,
    // icoParticipantCount: null,
    // tokenSymbol: null,
    // tokenBalanceUser: null,
    // etherBalanceUser: null,
    // name: null,
    // decimals: null,
    // tokenHolders: null,
  },
  proposalManagementInstance: null,
  requestManagementInstance: null,
  icoContractInstance: null,
  proposals: [],
  allRequests: [],
  contractFee: null,
  tokenHolder: false,
  boardMember: false,
}
